# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3eee49668e0021d0f32dc4928420918954f08243b2214bcde003461d74e06261a47b1a76d927eeece185fa17d4302f73550a407194c096897a42aafe05135287

test:
  secret_key_base: dee0d21d20288eb5f97e33e0f8ce50b800c583df0c6b5d602f1f1f34a036e87d2f8f6758799ceb434dca2368c3115af8153659b51754e4ba7a46dc57e383bf50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
